name: Pull request title format check

# - Note: By default, a workflow only runs when a pull_request's activity type is opened, synchronize, or reopened
# - Additional "closed" activity type is added

on:
  pull_request:
    types: []
#     types: [opened, synchronize, reopened, closed]

# - Run only if the Pull request is merged
# - Checkout self.
# - Run the release file ith proper arguments is_pull_request_correct 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: PR title check
        id: prTitleCheck
        uses:  ./.github/actions/check-pr-title
        with:
          REPO_NAME: ${{ github.event.repository.name }}  
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_NUMBER: ${{ github.event.pull_request.number }}    
          ACCESS_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
          USER_NAME: ${{ github.repository }}
          ACTION_TYPE: ${{ github.event.action }}
          AUTHOR_NAME: ${{ github.actor }}
