name: Create Release

# - on push or commit to master branch

on:
  push:
    branches: [ master ]

# - Checkout self.
# - Run the release file with proper arguments

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        id: createReleaseId
        uses:  ./.github/actions/create-release
        with:
          REPO_NAME: ${{ github.event.repository.name }}  
          ACCESS_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
          USER_NAME: ${{ github.repository }}
          AUTHOR_NAME: ${{ github.actor }}
