name: PyLint Runner

on:
  push:
    paths:
      - '**.py'
  pull_request:
    branches:
      - master
    paths:
      - '**.py'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Run Pylint
      run: |
        python ./.github/actions/pylint/lint.py --path . --threshold 2 --action github.event.action
